name: release

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ${{ env.GOPATH }}/src/k8s.io/autoscaler
      - name: Generate
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/recluster/gorecluster
        run: |
          go run github.com/Khan/genqlient
      - name: Build
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler
        run: |
          make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler/cluster-autoscaler-amd64
            ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler/cluster-autoscaler-arm64
          body: Cluster Autoscaler for reCluster