name: release

on:
  push:
    tags: ['v*.*.*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOPATH: ${{ github.workspace }}/go
  DOCKER_BUILDKIT: 1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Docker buildx
        run: |
          docker buildx create --use
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/autoscaler
      - name: Install dependencies
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler
        run: |
          go mod vendor
      - name: Generate
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/recluster/gorecluster
        run: |
          go run github.com/Khan/genqlient
      - name: Build binaries
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler
        run: |
          make BUILD_TAGS=recluster all
      - name: Build Docker amd64 image
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -f Dockerfile.amd64 \
            --tag recluster/cluster-autoscaler:latest \
            --output "type=docker,push=false,dest=cluster-autoscaler.amd64.tar.gz" \
            .
      - name: Build Docker arm64 image
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -f Dockerfile.arm64 \
            --tag recluster/cluster-autoscaler:latest \
            --output "type=docker,push=false,dest=cluster-autoscaler.arm64.tar.gz" \
            .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler/cluster-autoscaler.amd64.tar.gz
            ${{ env.GOPATH }}/src/k8s.io/autoscaler/cluster-autoscaler/cluster-autoscaler.arm64.tar.gz
